Fix deeply nested module imports
cloudflare/wrangler pull request #1764
Opened 2021-02-10 00:05 UTC by Electroid

In modules mode, when importing a file in a directory, it would get uploaded incorrectly.

`index.mjs`:
```js
import file from "./assets/file.txt"
```

`FormData`:
Before: `file.txt => "..."`
Now: `assets/file.txt => "..."`

2021-02-10 16:19 UTC, xortive commented on src/upload/form/mod.rs
> +                                .display()
This should use the `to_str` method of path and return an error if the conversion fails (due to non-UTF-8 in the path name)

2021-02-10 16:21 UTC, xortive commented on src/upload/form/mod.rs
> +                            log::info!("Adding module {}", name);
would be nice to include the path here as well

2021-02-10 16:23 UTC, xortive commented on src/upload/form/mod.rs
> +                                .display()
presumably for a path like like

`/home/matt/worker/dist/nested/nested/index.js`

This returns `nested/nested/index.js`?

2021-02-10 16:23 UTC, xortive requested changes
Nice catch, just handle the UTF-8 thing and I'll merge

2021-02-11 18:52 UTC, Electroid commented
Realized the previous approach would not work on Windows machines, so had to add a dependency to help us out.

2021-03-08 14:21 UTC, xortive commented
@Electroid could you rebase this on the `malonso/modules-rc` branch? I split that out from the old `modules-do` branch, and it looks like this PR is trying to add the durable objects support back in along with your fixes.

2021-03-08 16:32 UTC, xortive approved these changes
Thanks @Electroid!

2021-03-08 17:30 UTC, merged