Remove package.json requirement for JS workers
cloudflare/wrangler pull request #1808
Opened 2021-03-09 05:10 UTC by lsrugo

Fixes issue #1715 
For now it uses index.js as the default entry point. Maybe there should be an option to change that.

2021-03-09 09:57 UTC, xtuc commented
Could you please add a unit test to cover your change?

2021-03-09 21:48 UTC, lsrugo770 commented
I updated the unit test by removing the step which creates the package.json, to make sure that it passes without that file

2021-04-02 22:06 UTC, Electroid requested changes
Hey @lsrugo770, thanks for working on this!

The team discussed this and one of the points of feedback that came up was the ability to specify the `main` path in the `wrangler.toml`. We've had issues in the past with hardcoded values, like `index.js`. Is that a change you would be willing to add to your PR? It would end up look something like this:

```toml
name = "cool-thing"
type = "javascript"
main = "dist/worker.mjs" # Optional, if not specified, then check package.json
```

If you're not up for this, totally understand as well. Appreciate the time you put into this :)

2021-04-03 00:10 UTC, lsrugo770 commented
Thank you for getting back to me. This is my first time using Rust, but I will give it a shot.

2021-04-07 05:29 UTC, lsrugo770 commented
I think it's done. Let me know if I missed something

2021-04-09 13:57 UTC, xortive commented on src/settings/toml/target.rs
> +    pub main: String,
nit: it would be nice if this was an `Option<String>`, and you used serde's `string_empty_as_none` for the entry in `manifest.rs`

2021-04-09 17:58 UTC, ytbigvinny27 approved these changes
The Greed and compromised will always jump first 🙄but soon♥️🔜🤌🏽🔝

2021-12-03 17:00 UTC, brunolca commented
hi! any update on this?

2022-05-21 07:50 UTC, threepointone commented
wrangler 2 requires an explicit entry point now, either via the `main` field in `wrangler.toml`, or as a cli arg. closing this PR.

2022-05-21 07:50 UTC, closed without merging